-- CreateEnum
CREATE TYPE "LeadCategory" AS ENUM ('MEDICAL_REPRESENTATIVE', 'RETAILER', 'WHOLESALER', 'DISTRIBUTOR', 'MARKETING', 'THIRD_PARTY', 'DOCTOR', 'FRANCHISE', 'BUSINESS', 'HOSPITAL', 'CLINIC', 'PHARMACY', 'LABORATORY', 'MANUFACTURER', 'CORPORATE', 'GOVERNMENT', 'OTHER');

-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "category" "LeadCategory";
